Repository gautamkrishnar/socli, pull requests merged in 2021-01, with the labels that each got.

#251 Integrate Welcome Bot
  .github/config.yml
Labels: DWOC, Level-1

#257 Add Template for Issues
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/proposal.md
Labels: DWOC, Level 2

#260 argcomplete
  requirements.txt
  setup.py
  socli/parser.py
Labels: DWOC, Level-5

#248 fix potential bug risks and anti-patterns
  socli/printer.py
  socli/search.py
  socli/socli.py
  socli/tui.py
  socli/user.py
Labels: DWOC, Level-3
